/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SvConsole7f21a9c4RouteImport } from './routes/sv-console-7f21a9c4'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PluginRouteImport } from './routes/plugin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstalacaoRouteImport } from './routes/instalacao'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SvConsole7f21a9c4IndexRouteImport } from './routes/sv-console-7f21a9c4.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SvConsole7f21a9c4UsuariosRouteImport } from './routes/sv-console-7f21a9c4.usuarios'
import { Route as SvConsole7f21a9c4PluginRouteImport } from './routes/sv-console-7f21a9c4.plugin'
import { Route as SvConsole7f21a9c4LojaRouteImport } from './routes/sv-console-7f21a9c4.loja'
import { Route as DashboardLicencaRouteImport } from './routes/dashboard.licenca'
import { Route as DashboardDownloadRouteImport } from './routes/dashboard.download'
import { Route as DashboardConfigRouteImport } from './routes/dashboard.config'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SvConsole7f21a9c4Route = SvConsole7f21a9c4RouteImport.update({
  id: '/sv-console-7f21a9c4',
  path: '/sv-console-7f21a9c4',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginRoute = PluginRouteImport.update({
  id: '/plugin',
  path: '/plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalacaoRoute = InstalacaoRouteImport.update({
  id: '/instalacao',
  path: '/instalacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SvConsole7f21a9c4IndexRoute = SvConsole7f21a9c4IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SvConsole7f21a9c4Route,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SvConsole7f21a9c4UsuariosRoute =
  SvConsole7f21a9c4UsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => SvConsole7f21a9c4Route,
  } as any)
const SvConsole7f21a9c4PluginRoute = SvConsole7f21a9c4PluginRouteImport.update({
  id: '/plugin',
  path: '/plugin',
  getParentRoute: () => SvConsole7f21a9c4Route,
} as any)
const SvConsole7f21a9c4LojaRoute = SvConsole7f21a9c4LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => SvConsole7f21a9c4Route,
} as any)
const DashboardLicencaRoute = DashboardLicencaRouteImport.update({
  id: '/licenca',
  path: '/licenca',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDownloadRoute = DashboardDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigRoute = DashboardConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/ajuda': typeof AjudaRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/faq': typeof FaqRoute
  '/instalacao': typeof InstalacaoRoute
  '/login': typeof LoginRoute
  '/plugin': typeof PluginRoute
  '/pricing': typeof PricingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recursos': typeof RecursosRoute
  '/reembolso': typeof ReembolsoRoute
  '/register': typeof RegisterRoute
  '/resultados': typeof ResultadosRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/success': typeof SuccessRoute
  '/sv-console-7f21a9c4': typeof SvConsole7f21a9c4RouteWithChildren
  '/termos': typeof TermosRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/licenca': typeof DashboardLicencaRoute
  '/sv-console-7f21a9c4/loja': typeof SvConsole7f21a9c4LojaRoute
  '/sv-console-7f21a9c4/plugin': typeof SvConsole7f21a9c4PluginRoute
  '/sv-console-7f21a9c4/usuarios': typeof SvConsole7f21a9c4UsuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sv-console-7f21a9c4/': typeof SvConsole7f21a9c4IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/ajuda': typeof AjudaRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/download': typeof DownloadRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/faq': typeof FaqRoute
  '/instalacao': typeof InstalacaoRoute
  '/login': typeof LoginRoute
  '/plugin': typeof PluginRoute
  '/pricing': typeof PricingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recursos': typeof RecursosRoute
  '/reembolso': typeof ReembolsoRoute
  '/register': typeof RegisterRoute
  '/resultados': typeof ResultadosRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/success': typeof SuccessRoute
  '/termos': typeof TermosRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/licenca': typeof DashboardLicencaRoute
  '/sv-console-7f21a9c4/loja': typeof SvConsole7f21a9c4LojaRoute
  '/sv-console-7f21a9c4/plugin': typeof SvConsole7f21a9c4PluginRoute
  '/sv-console-7f21a9c4/usuarios': typeof SvConsole7f21a9c4UsuariosRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sv-console-7f21a9c4': typeof SvConsole7f21a9c4IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/ajuda': typeof AjudaRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/faq': typeof FaqRoute
  '/instalacao': typeof InstalacaoRoute
  '/login': typeof LoginRoute
  '/plugin': typeof PluginRoute
  '/pricing': typeof PricingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recursos': typeof RecursosRoute
  '/reembolso': typeof ReembolsoRoute
  '/register': typeof RegisterRoute
  '/resultados': typeof ResultadosRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/success': typeof SuccessRoute
  '/sv-console-7f21a9c4': typeof SvConsole7f21a9c4RouteWithChildren
  '/termos': typeof TermosRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/licenca': typeof DashboardLicencaRoute
  '/sv-console-7f21a9c4/loja': typeof SvConsole7f21a9c4LojaRoute
  '/sv-console-7f21a9c4/plugin': typeof SvConsole7f21a9c4PluginRoute
  '/sv-console-7f21a9c4/usuarios': typeof SvConsole7f21a9c4UsuariosRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sv-console-7f21a9c4/': typeof SvConsole7f21a9c4IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afiliados'
    | '/ajuda'
    | '/checkout'
    | '/contato'
    | '/dashboard'
    | '/download'
    | '/esqueci-senha'
    | '/faq'
    | '/instalacao'
    | '/login'
    | '/plugin'
    | '/pricing'
    | '/privacidade'
    | '/recursos'
    | '/reembolso'
    | '/register'
    | '/resultados'
    | '/sobre'
    | '/status'
    | '/success'
    | '/sv-console-7f21a9c4'
    | '/termos'
    | '/dashboard/config'
    | '/dashboard/download'
    | '/dashboard/licenca'
    | '/sv-console-7f21a9c4/loja'
    | '/sv-console-7f21a9c4/plugin'
    | '/sv-console-7f21a9c4/usuarios'
    | '/dashboard/'
    | '/sv-console-7f21a9c4/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliados'
    | '/ajuda'
    | '/checkout'
    | '/contato'
    | '/download'
    | '/esqueci-senha'
    | '/faq'
    | '/instalacao'
    | '/login'
    | '/plugin'
    | '/pricing'
    | '/privacidade'
    | '/recursos'
    | '/reembolso'
    | '/register'
    | '/resultados'
    | '/sobre'
    | '/status'
    | '/success'
    | '/termos'
    | '/dashboard/config'
    | '/dashboard/download'
    | '/dashboard/licenca'
    | '/sv-console-7f21a9c4/loja'
    | '/sv-console-7f21a9c4/plugin'
    | '/sv-console-7f21a9c4/usuarios'
    | '/dashboard'
    | '/sv-console-7f21a9c4'
  id:
    | '__root__'
    | '/'
    | '/afiliados'
    | '/ajuda'
    | '/checkout'
    | '/contato'
    | '/dashboard'
    | '/download'
    | '/esqueci-senha'
    | '/faq'
    | '/instalacao'
    | '/login'
    | '/plugin'
    | '/pricing'
    | '/privacidade'
    | '/recursos'
    | '/reembolso'
    | '/register'
    | '/resultados'
    | '/sobre'
    | '/status'
    | '/success'
    | '/sv-console-7f21a9c4'
    | '/termos'
    | '/dashboard/config'
    | '/dashboard/download'
    | '/dashboard/licenca'
    | '/sv-console-7f21a9c4/loja'
    | '/sv-console-7f21a9c4/plugin'
    | '/sv-console-7f21a9c4/usuarios'
    | '/dashboard/'
    | '/sv-console-7f21a9c4/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfiliadosRoute: typeof AfiliadosRoute
  AjudaRoute: typeof AjudaRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  FaqRoute: typeof FaqRoute
  InstalacaoRoute: typeof InstalacaoRoute
  LoginRoute: typeof LoginRoute
  PluginRoute: typeof PluginRoute
  PricingRoute: typeof PricingRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecursosRoute: typeof RecursosRoute
  ReembolsoRoute: typeof ReembolsoRoute
  RegisterRoute: typeof RegisterRoute
  ResultadosRoute: typeof ResultadosRoute
  SobreRoute: typeof SobreRoute
  StatusRoute: typeof StatusRoute
  SuccessRoute: typeof SuccessRoute
  SvConsole7f21a9c4Route: typeof SvConsole7f21a9c4RouteWithChildren
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sv-console-7f21a9c4': {
      id: '/sv-console-7f21a9c4'
      path: '/sv-console-7f21a9c4'
      fullPath: '/sv-console-7f21a9c4'
      preLoaderRoute: typeof SvConsole7f21a9c4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugin': {
      id: '/plugin'
      path: '/plugin'
      fullPath: '/plugin'
      preLoaderRoute: typeof PluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalacao': {
      id: '/instalacao'
      path: '/instalacao'
      fullPath: '/instalacao'
      preLoaderRoute: typeof InstalacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sv-console-7f21a9c4/': {
      id: '/sv-console-7f21a9c4/'
      path: '/'
      fullPath: '/sv-console-7f21a9c4/'
      preLoaderRoute: typeof SvConsole7f21a9c4IndexRouteImport
      parentRoute: typeof SvConsole7f21a9c4Route
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/sv-console-7f21a9c4/usuarios': {
      id: '/sv-console-7f21a9c4/usuarios'
      path: '/usuarios'
      fullPath: '/sv-console-7f21a9c4/usuarios'
      preLoaderRoute: typeof SvConsole7f21a9c4UsuariosRouteImport
      parentRoute: typeof SvConsole7f21a9c4Route
    }
    '/sv-console-7f21a9c4/plugin': {
      id: '/sv-console-7f21a9c4/plugin'
      path: '/plugin'
      fullPath: '/sv-console-7f21a9c4/plugin'
      preLoaderRoute: typeof SvConsole7f21a9c4PluginRouteImport
      parentRoute: typeof SvConsole7f21a9c4Route
    }
    '/sv-console-7f21a9c4/loja': {
      id: '/sv-console-7f21a9c4/loja'
      path: '/loja'
      fullPath: '/sv-console-7f21a9c4/loja'
      preLoaderRoute: typeof SvConsole7f21a9c4LojaRouteImport
      parentRoute: typeof SvConsole7f21a9c4Route
    }
    '/dashboard/licenca': {
      id: '/dashboard/licenca'
      path: '/licenca'
      fullPath: '/dashboard/licenca'
      preLoaderRoute: typeof DashboardLicencaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/download': {
      id: '/dashboard/download'
      path: '/download'
      fullPath: '/dashboard/download'
      preLoaderRoute: typeof DashboardDownloadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/config': {
      id: '/dashboard/config'
      path: '/config'
      fullPath: '/dashboard/config'
      preLoaderRoute: typeof DashboardConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardConfigRoute: typeof DashboardConfigRoute
  DashboardDownloadRoute: typeof DashboardDownloadRoute
  DashboardLicencaRoute: typeof DashboardLicencaRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfigRoute: DashboardConfigRoute,
  DashboardDownloadRoute: DashboardDownloadRoute,
  DashboardLicencaRoute: DashboardLicencaRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SvConsole7f21a9c4RouteChildren {
  SvConsole7f21a9c4LojaRoute: typeof SvConsole7f21a9c4LojaRoute
  SvConsole7f21a9c4PluginRoute: typeof SvConsole7f21a9c4PluginRoute
  SvConsole7f21a9c4UsuariosRoute: typeof SvConsole7f21a9c4UsuariosRoute
  SvConsole7f21a9c4IndexRoute: typeof SvConsole7f21a9c4IndexRoute
}

const SvConsole7f21a9c4RouteChildren: SvConsole7f21a9c4RouteChildren = {
  SvConsole7f21a9c4LojaRoute: SvConsole7f21a9c4LojaRoute,
  SvConsole7f21a9c4PluginRoute: SvConsole7f21a9c4PluginRoute,
  SvConsole7f21a9c4UsuariosRoute: SvConsole7f21a9c4UsuariosRoute,
  SvConsole7f21a9c4IndexRoute: SvConsole7f21a9c4IndexRoute,
}

const SvConsole7f21a9c4RouteWithChildren =
  SvConsole7f21a9c4Route._addFileChildren(SvConsole7f21a9c4RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfiliadosRoute: AfiliadosRoute,
  AjudaRoute: AjudaRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DownloadRoute: DownloadRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  FaqRoute: FaqRoute,
  InstalacaoRoute: InstalacaoRoute,
  LoginRoute: LoginRoute,
  PluginRoute: PluginRoute,
  PricingRoute: PricingRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecursosRoute: RecursosRoute,
  ReembolsoRoute: ReembolsoRoute,
  RegisterRoute: RegisterRoute,
  ResultadosRoute: ResultadosRoute,
  SobreRoute: SobreRoute,
  StatusRoute: StatusRoute,
  SuccessRoute: SuccessRoute,
  SvConsole7f21a9c4Route: SvConsole7f21a9c4RouteWithChildren,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
